"""records 테이블 초기화 스크립트

word_oracle.py 로 쌓인 게임 기록을 전부 지우고 record_id 를 1번부터 다시 시작시킨다.
지운 데이터는 되돌릴 수 없으므로 실행 전에 확인을 받는다.
"""

import os

import oracledb
from dotenv import load_dotenv

# 스크립트 위치 기준으로 경로를 잡아야 어디서 실행해도 .env 를 찾음
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
load_dotenv(os.path.join(BASE_DIR, ".env"))

password = os.getenv("ORACLE_PASSWORD", "54321")

with oracledb.connect(
    user="python_user", password=password, dsn="localhost:1521/FREEPDB1"
) as conn:
    with conn.cursor() as cursor:

        # 지우기 전에 몇 건이 사라지는지 먼저 보여준다
        cursor.execute("select count(*) from records")
        (total,) = cursor.fetchone()

        if total == 0:
            print("records 테이블이 이미 비어 있음")
            raise SystemExit

        print(f"records 테이블에 {total}건이 있음. 전부 삭제됩니다.")
        if input("정말 초기화할까요? (y/N) : ").strip().lower() != "y":
            print("취소함")
            raise SystemExit

        # 1) 데이터 전부 삭제
        cursor.execute("delete from records")
        deleted = cursor.rowcount
        conn.commit()

        # 2) record_id(IDENTITY) 를 1번부터 다시 시작시킴
        #    delete 만 하면 다음 입력이 7, 8 ... 처럼 이어져서 따로 재시작시켜야 함
        #    DDL 이라 자동 commit 되고 rollback 이 안 됨
        cursor.execute(
            """alter table records
               modify (record_id generated by default as identity (start with 1))"""
        )

print(f"초기화 완료 : {deleted}건 삭제, record_id 는 1번부터 다시 시작")
