import os
import random
import time
from datetime import datetime

import oracledb
from dotenv import load_dotenv

# 스크립트 위치 기준으로 경로를 잡아야 어디서 실행해도 파일을 찾음
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
WORD_FILE = os.path.join(BASE_DIR, "data", "word.txt")

# .env 를 읽어야 os.getenv 로 비밀번호가 넘어옴 (스크립트 위치 기준으로 지정)
load_dotenv(os.path.join(BASE_DIR, ".env"))

QUIZ_COUNT = 5
PASS_LINE = 3

with open(WORD_FILE, "r", encoding="utf-8") as f:
    contents = [line.strip() for line in f if line.strip()]

# choices는 중복을 허용해서 뽑음. 이럴때는 sample(contents, 5)를 사용하는게 더 좋음
contentList = random.sample(contents, k=QUIZ_COUNT)

start = time.time()
trueAnswer = 0
count = 0
while count < QUIZ_COUNT:
    pickedOne = contentList[count]
    print(f"Q{count+1} : {pickedOne}")
    answer = input("단어 입력해 : ")
    count += 1
    if answer == pickedOne:
        print("정답!!!")
        trueAnswer += 1
    else:
        print("오타!!!")

end = time.time()
et = format(end - start, ".3f")

if trueAnswer >= PASS_LINE:
    result = "합격"
else:
    result = "불합격"

print(f"게임시간 : {et}, 정답개수 : {trueAnswer}, 합격여부 : {result}")


# db에 저장하는거 추가!
password = os.getenv("ORACLE_PASSWORD", "54321")

with oracledb.connect(
    user="python_user", password=password, dsn="localhost:1521/FREEPDB1"
) as conn:
    with conn.cursor() as cursor:

        try:
            cursor.execute(
                """create table if not exists records(
                    record_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    corr_cnt integer,
                    record   varchar2(20),
                    regdate  varchar2(30)
                )"""
            )
        except oracledb.DatabaseError as e:
            # e.args는 튜플이라 (error_obj) 로는 못 꺼냄 -> 콤마를 찍어 언패킹
            (error_obj,) = e.args
            # ORA-00955 : 이미 같은 이름의 객체가 있음 (if not exists를 안 쓸 때 대비)
            if error_obj.code == 955:
                print(error_obj.message)
            else:
                raise

        nowDateTime = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # 오라클 바인드 변수는 ? 가 아니라 :1, :2, :3
        sql = "insert into records(corr_cnt, record, regdate) values(:1, :2, :3)"
        cursor.execute(sql, (trueAnswer, et, nowDateTime))

        # commit 안 하면 커넥션이 닫힐 때 롤백되어 저장이 안 됨
        conn.commit()

print("기록 저장 완료")
